apiVersion: v1
kind: Service
metadata:
  name: neuro-frontend
  namespace: neurocompute
spec:
  selector:
    app: neuro-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
